#!/usr/bin/env bash

# Create a regex for a conventional commit.
conventional_commit_regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z \-]+\))?!?: .+$"

# Get the commit message (the parameter we're given is just the path to the
# temporary file which holds the message).
commit_message=$(cat "$1")

# Check the message, if we match, all good baby.
if [[ "$commit_message" =~ $conventional_commit_regex ]]; then
   printf "\033[31mCommit message meets Conventional Commit standards...\033[0m\n"
   exit 0
fi

# Uh-oh, this is not a conventional commit, show an example and link to the spec.
printf "\033[31mThe commit message does not meet the Conventional Commit standard\033[0m\n"
printf "An example of a valid message is: \n"
printf "  feat(login): add the 'remember me' button\n"
printf "More details at: https://www.conventionalcommits.org/en/v1.0.0/#summary"
exit 1