#!/usr/bin/env bash
set -euo pipefail
LC_ALL=C

validate_branch_name() {
    local branch="$1"
    local regex="^(feature|bugfix)\/[0-9]+-[a-z0-9]+([-_][a-z0-9]+)*$|^(ci|chore|infra)\/[a-z0-9]+([-_][a-z0-9]+)*$"
    local error_message="
    \033[31m✘ Invalid branch name detected:

    \033[2mBranch names must follow these rules:
    1. Feature or bugfix branches must include a numeric ticket ID and a short description:
       - Example: feature/123-add-login, bugfix/456-fix-crash.
    2. CI, chore, or infra branches must include a short description:
       - Example: ci/add-linting, chore/update-dependencies, infra/refactor-deployment.

    Your branch: '$branch' does not match these rules.
    Please rename your branch and try again.
    "

    if [[ ! "$branch" =~ $regex ]]; then
        printf "%s" "$error_message" >&2
        exit 1
    fi
}

main() {
    local branch_name
    branch_name="$(git rev-parse --abbrev-ref HEAD)" || {
        printf "\033[31m✘ Error: Failed to retrieve the current branch name." >&2
        exit 1
    }
    validate_branch_name "$branch_name"
}

main "$@"